### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by WaluigiBSOD** [WaluigiBSOD/dm64-password-decoder#1]
# Code

- [x] Look for redundant/unnecessary validity checks and remove them
- [x] Add an empty `.nojekyll` file in the root of the website
- [x] Add a `404.html` 404 error handler in the root of the website that redirects to the main page
